title-bold: colin
title-normal: zone
email: colin.pilloud@gmail.com
description: Software developer from Denver
url: "http://colin.zone" # the base hostname & protocol for your site
author: Colin Pilloud

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

tiles-source: posts # accepts "posts" or "pages"

github_url: https://github.com/colinpilloud
instagram_url: https://instagram.com/colinpilloud
twitter_url: https://twitter.com/colinpilloud
linkedin_url: https://www.linkedin.com/in/colinpilloud

markdown: kramdown

twitter:
  username: colinpilloud

sass:
  style: compressed

exclude: ["Gemfile", "Gemfile.lock", "README.md"]