# Dependencies
markdown:	redcarpet
highlighter:	rouge

# Permalinks
permalink:	/:title

# Setup
title:		Techscum
description:	'tech/java/ruby stuff, from my brain to yours'
url:		http://blog.colinpilloud.com

author:
  name:		'Colin Pilloud'
  url:		colinpilloud.com

paginate:	5

comments: true

social:
  - icon:	twitter
    url:	https://twitter.com/colinpilloud
    desc:	Twitter

menu:
  - title:	Home
    url:	/

  - title:	About
    url: /about

copyright:
  author:	Colin Pilloud
  url:		colinpilloud.com

assets:
  js_compressor:  yui
  css_compressor: yui