# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/:title

# Setup
title:		Techscum
description:	'dumb tech stuff'
url:		http://colinpilloud.github.io

author:
  name:		'Colin Pilloud'
  url:		colinpilloud.com

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/colinpilloud
    desc:	Twitter

menu:
  - title:	Home
    url:	/

  - title:	About
    url: /about

copyright:
  author:	Colin Pilloud
  url:		colinpilloud.com
