# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/:title

# Setup
title:		Spoarts
description:	'A spoarts blog for spoarts fans and also non-spoarts fans'
url:		http://colinpilloud.github.io

author:
  name:		'Colin Pilloud'
  url:		colinpilloud.com

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/colinpilloud
    desc:	Twitter

menu:
  - title:	Home
    url:	/

copyright:
  author:	Colin Pilloud
  url:		colinpilloud.com
